### ISSUE TITLE
Install/first-run fails on Java 9 with ClassCastException

### ISSUE THREAD

**Issue by kirked** [boot-clj/boot#525]
I realise this is premature, but the release of Java 9 fast approaches...

I downloaded `boot.sh` on current Linux Mint, then ran this:

```
$ boot repl
Downloading https://github.com/boot-clj/boot/releases/download/2.6.0/boot.jar...
Exception in thread "main" java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader (in module: java.base) cannot be cast to java.net.URLClassLoader (in module: java.base)
	at Boot.loadJar(Boot.java:228)
	at Boot.main(Boot.java:254)
doug@twist ~/code/dashboard $ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by tobias** [comment]
This is caused by the app classloader being replaced in Java 9 - see https://github.com/tobias/clojure-java-9/issues/3

**Comment by tobias** [comment]
This should be fixed by https://github.com/boot-clj/boot/pull/539 and https://github.com/boot-clj/boot-bin/pull/4.

**Comment by ghadishayban** [comment]
I tested this with JDK 7, 8, & 9 and it worked properly.

**Comment by laseray** [comment]
This is not fixed for me. Boot still fails to run under Java 9 (on Linux Mint 18.3) with latest snapshot. Gives the same Classloader error.

#http://boot-clj.com
#Fri Jan 26 15:26:16 EST 2018
BOOT_CLOJURE_NAME=org.clojure/clojure
BOOT_COLOR=yes
BOOT_VERSION=2.8.0-SNAPSHOT
BOOT_CLOJURE_VERSION=1.9.0

java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by alexander-yakushev** [comment]
@laseray @prakashksinha Make sure you re-download the Boot binary file (boot.sh or boot.exe, see here https://github.com/boot-clj/boot#install)

**Comment by Bost** [comment]
I've got the same problem under java 1.10:
```
$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
$ boot -v
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at Boot.loadJar(Boot.java:228)
	at Boot.main(Boot.java:254)
```

**Comment by alexander-yakushev** [comment]
@Bost are you using the latest Boot binary?

**Comment by Bost** [comment]
@alexander-yakushev That was the problem :) You may consider closing this issue. Thanx.
